version: '3.4'

services:
  django-base:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    expose:
      - 8000
    env_file:
      - .env
      - .django.env
    volumes:
      - media_files:/home/django/mediafiles
      - static_files:/home/django/staticfiles
      - sqlite_data:/home/django/sqlite3

  nginx-proxy:
    build: nginx
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - django-base

volumes:
  sqlite_data:
  media_files:
  static_files:
